theme: jekyll-theme-minimal
title                    : "COVID19 trend abnormally" 
repository               : " " 
search                   : true 
search_full_content      : true 
author:
  github : "PAHO-ghe" 
